// <auto-generated />
using System;
using Felion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Felion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FelionDbContext))]
    [Migration("20260916133349_AddEventRegistrations")]
    partial class AddEventRegistrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Felion.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorDiscordUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_discord_user_id");

                    b.Property<Guid?>("ActorMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_member_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("ActorMemberId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_logs_actor", "(actor_type = 'WebMember' AND actor_member_id IS NOT NULL AND actor_discord_user_id IS NULL) OR (actor_type = 'DiscordMember' AND actor_member_id IS NULL AND actor_discord_user_id IS NOT NULL) OR (actor_type = 'System' AND actor_member_id IS NULL AND actor_discord_user_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionPromptSnapshot")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("question_prompt_snapshot");

                    b.Property<string>("QuestionTypeSnapshot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_type_snapshot");

                    b.Property<decimal?>("ScoreValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("score_value");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("TextValue")
                        .HasColumnType("text")
                        .HasColumnName("text_value");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("evaluation_answers", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_answers_value", "(question_type_snapshot = 'Score' AND text_value IS NULL) OR (question_type_snapshot = 'Text' AND score_value IS NULL)");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationForm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<string>("ReviewerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reviewer_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("evaluation_forms", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_forms_reviewer_type", "reviewer_type IN ('Peer', 'Mentor')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("evaluation_periods", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_periods_status", "status IN ('Draft', 'Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("prompt");

                    b.Property<decimal?>("ScoreMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("score_max");

                    b.Property<decimal?>("ScoreMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("score_min");

                    b.Property<int?>("TextMaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("text_max_length");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FormId", "Order")
                        .IsUnique();

                    b.ToTable("evaluation_questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_questions_configuration", "(type = 'Score' AND score_min IS NOT NULL AND score_max IS NOT NULL AND score_min <= score_max AND text_max_length IS NULL) OR (type = 'Text' AND score_min IS NULL AND score_max IS NULL AND text_max_length IS NOT NULL AND text_max_length > 0)");

                            t.HasCheckConstraint("ck_evaluation_questions_order", "order_number > 0");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid?>("ReviewerCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_candidate_id");

                    b.Property<Guid?>("ReviewerMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_member_id");

                    b.Property<string>("ReviewerNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewer_name_snapshot");

                    b.Property<string>("ReviewerStudentIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reviewer_student_id_snapshot");

                    b.Property<string>("ReviewerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reviewer_type");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("TargetCandidateId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_candidate_id");

                    b.Property<string>("TargetNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_name_snapshot");

                    b.Property<string>("TargetStudentIdSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_student_id_snapshot");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReviewerCandidateId");

                    b.HasIndex("ReviewerMemberId");

                    b.HasIndex("TargetCandidateId");

                    b.HasIndex("PeriodId", "FormId");

                    b.HasIndex("FormId", "ReviewerCandidateId", "TargetCandidateId")
                        .IsUnique()
                        .HasFilter("reviewer_candidate_id IS NOT NULL AND target_candidate_id IS NOT NULL");

                    b.HasIndex("FormId", "ReviewerMemberId", "TargetCandidateId")
                        .IsUnique()
                        .HasFilter("reviewer_member_id IS NOT NULL AND target_candidate_id IS NOT NULL");

                    b.ToTable("evaluation_submissions", null, t =>
                        {
                            t.HasCheckConstraint("ck_evaluation_submissions_reviewer", "(reviewer_type = 'Peer' AND reviewer_candidate_id IS NOT NULL AND reviewer_member_id IS NULL) OR (reviewer_type = 'Mentor' AND reviewer_member_id IS NOT NULL AND reviewer_candidate_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowMultiplePositions")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_multiple_positions");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_member_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMemberId");

                    b.HasIndex("StartsAt");

                    b.HasIndex("Status");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_status", "status IN ('Draft', 'Published', 'RegistrationClosed', 'InProgress', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Events.EventPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RequiredDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_department_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RequiredDepartmentId");

                    b.HasIndex("EventId", "SortOrder");

                    b.ToTable("event_positions", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_positions_capacity", "capacity > 0");

                            t.HasCheckConstraint("ck_event_positions_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Events.EventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_member_id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by_member_id");

                    b.Property<Guid>("EventPositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_position_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset?>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByMemberId");

                    b.HasIndex("DecidedByMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("EventPositionId", "MemberId")
                        .IsUnique()
                        .HasFilter("status IN ('Pending', 'Approved', 'Assigned')");

                    b.HasIndex("EventPositionId", "Status");

                    b.ToTable("event_registrations", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_registrations_status", "status IN ('Pending', 'Approved', 'Rejected', 'Cancelled', 'Assigned')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Identity.DiscordIdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("DiscordUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("discord_user_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("SubjectId")
                        .IsUnique();

                    b.ToTable("discord_identity_links", null, t =>
                        {
                            t.HasCheckConstraint("ck_discord_identity_links_subject_type", "subject_type IN ('Member', 'Probation')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Identity.DiscordRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("DiscordRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("discord_role_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("RoleNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_name_snapshot");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "SubjectKey")
                        .IsUnique();

                    b.ToTable("discord_role_mappings", null, t =>
                        {
                            t.HasCheckConstraint("ck_discord_role_mappings_kind", "kind IN ('Position', 'Probation', 'Department', 'Generation', 'ProbationTeam')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Identity.DiscordSyncJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("operation");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("subject_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("SubjectType", "SubjectId", "Operation", "Status");

                    b.ToTable("discord_sync_jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_discord_sync_jobs_attempts", "attempts >= 0");

                            t.HasCheckConstraint("ck_discord_sync_jobs_operation", "operation IN ('SynchronizeRoles', 'ClearManagedRoles', 'KickUser')");

                            t.HasCheckConstraint("ck_discord_sync_jobs_status", "status IN ('Pending', 'Running', 'Succeeded', 'Failed')");

                            t.HasCheckConstraint("ck_discord_sync_jobs_subject_type", "subject_type IN ('Member', 'Probation')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Members.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCore")
                        .HasColumnType("boolean")
                        .HasColumnName("is_core");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("IsCore")
                        .IsUnique()
                        .HasFilter("is_core = true");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("departments", null, t =>
                        {
                            t.HasCheckConstraint("ck_departments_core_slug", "NOT is_core OR slug = 'core'");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f8d4a6b-6a1d-4b5c-9ef7-8b9b8d1f4b21"),
                            IsActive = true,
                            IsCore = true,
                            Name = "Core",
                            Slug = "core"
                        });
                });

            modelBuilder.Entity("Felion.Domain.Members.Generation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("generations", (string)null);
                });

            modelBuilder.Entity("Felion.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClubEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("club_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("position");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClubEmail")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GenerationId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_position", "position IN ('Admin', 'Core', 'Member')");

                            t.HasCheckConstraint("ck_members_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Probation.ProbationCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<Guid>("GenerationId")
                        .HasColumnType("uuid")
                        .HasColumnName("generation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("GenerationId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("probation_candidates", null, t =>
                        {
                            t.HasCheckConstraint("ck_probation_candidates_status", "status IN ('Active', 'Passed', 'Failed', 'Archived')");
                        });
                });

            modelBuilder.Entity("Felion.Domain.Probation.ProbationTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("probation_teams", (string)null);
                });

            modelBuilder.Entity("Felion.Domain.Probation.TeamMentor", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.HasKey("TeamId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("team_mentors", (string)null);
                });

            modelBuilder.Entity("Felion.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("ActorMemberId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationAnswer", b =>
                {
                    b.HasOne("Felion.Domain.Evaluation.EvaluationQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Felion.Domain.Evaluation.EvaluationSubmission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationForm", b =>
                {
                    b.HasOne("Felion.Domain.Evaluation.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationQuestion", b =>
                {
                    b.HasOne("Felion.Domain.Evaluation.EvaluationForm", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Evaluation.EvaluationSubmission", b =>
                {
                    b.HasOne("Felion.Domain.Evaluation.EvaluationForm", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Evaluation.EvaluationPeriod", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Probation.ProbationCandidate", null)
                        .WithMany()
                        .HasForeignKey("ReviewerCandidateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("ReviewerMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Felion.Domain.Probation.ProbationCandidate", null)
                        .WithMany()
                        .HasForeignKey("TargetCandidateId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Felion.Domain.Events.Event", b =>
                {
                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Events.EventPosition", b =>
                {
                    b.HasOne("Felion.Domain.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Members.Department", null)
                        .WithMany()
                        .HasForeignKey("RequiredDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Felion.Domain.Events.EventRegistration", b =>
                {
                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("AssignedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("DecidedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Felion.Domain.Events.EventPosition", null)
                        .WithMany()
                        .HasForeignKey("EventPositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Members.Member", b =>
                {
                    b.HasOne("Felion.Domain.Members.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Members.Generation", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Felion.Domain.Probation.ProbationCandidate", b =>
                {
                    b.HasOne("Felion.Domain.Members.Department", null)
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Members.Generation", null)
                        .WithMany()
                        .HasForeignKey("GenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Probation.ProbationTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Felion.Domain.Probation.TeamMentor", b =>
                {
                    b.HasOne("Felion.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Felion.Domain.Probation.ProbationTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
